var tree = [["Icecave",,"",
                [["Siphon","Icecave\/Siphon.html","",
                [["Atom","Icecave\/Siphon\/Atom.html","",
                [["AtomEntryInterface","Icecave\/Siphon\/Atom\/AtomEntryInterface.html","",
                [        ]],["AtomReaderInterface","Icecave\/Siphon\/Atom\/AtomReaderInterface.html","",
                [        ]],["AtomResultInterface","Icecave\/Siphon\/Atom\/AtomResultInterface.html","",
                [        ]]        ]],["Exception","Icecave\/Siphon\/Exception.html","",
                [["ServiceUnavailableException","Icecave\/Siphon\/Exception\/ServiceUnavailableException.html"," < RuntimeException",
                [        ]]        ]],["Player","Icecave\/Siphon\/Player.html","",
                [["InjuryInterface","Icecave\/Siphon\/Player\/InjuryInterface.html","",
                [        ]],["PlayerInterface","Icecave\/Siphon\/Player\/PlayerInterface.html","",
                [        ]],["PlayerReaderInterface","Icecave\/Siphon\/Player\/PlayerReaderInterface.html","",
                [        ]],["SeasonDetailsInterface","Icecave\/Siphon\/Player\/SeasonDetailsInterface.html","",
                [        ]],["StatisticsInterface","Icecave\/Siphon\/Player\/StatisticsInterface.html","",
                [        ]],["StatisticsReaderInterface","Icecave\/Siphon\/Player\/StatisticsReaderInterface.html","",
                [        ]]        ]],["Schedule","Icecave\/Siphon\/Schedule.html","",
                [["CompetitionCollectionInterface","Icecave\/Siphon\/Schedule\/CompetitionCollectionInterface.html","",
                [        ]],["CompetitionInterface","Icecave\/Siphon\/Schedule\/CompetitionInterface.html","",
                [        ]],["CompetitionStatus","Icecave\/Siphon\/Schedule\/CompetitionStatus.html"," < AbstractEnumeration",
                [        ]],["ScheduleInterface","Icecave\/Siphon\/Schedule\/ScheduleInterface.html","",
                [        ]],["ScheduleLimit","Icecave\/Siphon\/Schedule\/ScheduleLimit.html"," < AbstractEnumeration",
                [        ]],["ScheduleReaderInterface","Icecave\/Siphon\/Schedule\/ScheduleReaderInterface.html","",
                [        ]],["SeasonInterface","Icecave\/Siphon\/Schedule\/SeasonInterface.html","",
                [        ]]        ]],["Score","Icecave\/Siphon\/Score.html","",
                [["BoxScore","Icecave\/Siphon\/Score\/BoxScore.html","",
                [["BoxScoreReaderInterface","Icecave\/Siphon\/Score\/BoxScore\/BoxScoreReaderInterface.html","",
                [        ]],["BoxScoreResultInterface","Icecave\/Siphon\/Score\/BoxScore\/BoxScoreResultInterface.html","",
                [        ]]        ]],["LiveScore","Icecave\/Siphon\/Score\/LiveScore.html","",
                [["InningResultInterface","Icecave\/Siphon\/Score\/LiveScore\/InningResultInterface.html","",
                [        ]],["InningSubType","Icecave\/Siphon\/Score\/LiveScore\/InningSubType.html"," < AbstractEnumeration",
                [        ]],["LiveScoreReaderInterface","Icecave\/Siphon\/Score\/LiveScore\/LiveScoreReaderInterface.html","",
                [        ]],["LiveScoreResultInterface","Icecave\/Siphon\/Score\/LiveScore\/LiveScoreResultInterface.html","",
                [        ]],["PeriodResultInterface","Icecave\/Siphon\/Score\/LiveScore\/PeriodResultInterface.html","",
                [        ]],["ScopeStatus","Icecave\/Siphon\/Score\/LiveScore\/ScopeStatus.html"," < AbstractEnumeration",
                [        ]]        ]],["InningInterface","Icecave\/Siphon\/Score\/InningInterface.html","",
                [        ]],["InningScoreInterface","Icecave\/Siphon\/Score\/InningScoreInterface.html","",
                [        ]],["InningStatisticsInterface","Icecave\/Siphon\/Score\/InningStatisticsInterface.html","",
                [        ]],["PeriodInterface","Icecave\/Siphon\/Score\/PeriodInterface.html","",
                [        ]],["PeriodType","Icecave\/Siphon\/Score\/PeriodType.html"," < AbstractEnumeration",
                [        ]],["ScopeInterface","Icecave\/Siphon\/Score\/ScopeInterface.html","",
                [        ]],["ScoreInterface","Icecave\/Siphon\/Score\/ScoreInterface.html","",
                [        ]],["TeamScoreInterface","Icecave\/Siphon\/Score\/TeamScoreInterface.html","",
                [        ]]        ]],["Team","Icecave\/Siphon\/Team.html","",
                [["TeamInterface","Icecave\/Siphon\/Team\/TeamInterface.html","",
                [        ]],["TeamReaderInterface","Icecave\/Siphon\/Team\/TeamReaderInterface.html","",
                [        ]]        ]],["Factory","Icecave\/Siphon\/Factory.html","",
                [        ]],["FactoryInterface","Icecave\/Siphon\/FactoryInterface.html","",
                [        ]],["PackageInfo","Icecave\/Siphon\/PackageInfo.html","",
                [        ]],["UrlBuilderInterface","Icecave\/Siphon\/UrlBuilderInterface.html","",
                [        ]],["XmlReaderInterface","Icecave\/Siphon\/XmlReaderInterface.html","",
                [        ]]        ]]        ]]        ]

